server:
  port: 8085

spring:
  application:
    name: eureka-review

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true

